project:
  type: website

website:
  title: "Data vizualization projects with R|Luke Albracht"
  search: true
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    toc: true
    contents:
      - About.qmd
      - API Connection Walkthrough.qmd
      - Plotting-sine-waves.qmd

format:
  html:
    theme: superhero
      
editor: visual

