project:
  type: website

website:
  title: "Data vizualization projects with R|Luke Albracht"
  search: true
  back-to-top-navigation: true
  navbar:
    style: "docked"
    search: true
    toc: true
    contents:
      - About.qmd
      - API-connection-walkthrough.qmd
      - Plotting-sine-waves.qmd

title-block-banner: "#27445C"
format: 
  html:
    smooth-scroll: true
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
css: styles.css
theme:
  light: [cosmo, assets/scripts/lightstyle.scss]
  dark: [cosmo, assets/scripts/darkstyle.scss]

