project:
  type: website

website:
  title: "Data vizualization projects with R|Luke Albracht"
  description: ""
  search: true
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - About.qmd
      - API Connection Walkthrough.qmd
      - Plotting-sine-waves.qmd

format:
  html:
    toc: true
    theme:
      light: superhero
      dark: darkly
      

editor: visual

